apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-vulkan-cache
  namespace: murakumo-system
  labels:
    app.kubernetes.io/name: llama-vulkan
    app.kubernetes.io/part-of: murakumo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
